### ISSUE TITLE
Copied styles don't match with the effect

### ISSUE THREAD

**Issue by matias-salgado** [emilkowalski/ui-snippets#39]
For example, the [borderMarker](https://github.com/emilkowalski/ui-snippets/blob/master/components/Snippets/borderMarker.js) effect gets this styles applied on the website:

![Untitled](https://user-images.githubusercontent.com/82465985/124339906-dffe8780-db87-11eb-8636-52d1a87dc280.png)

but the copied CSS styles don't match:

```css
.exampleClass {
  display: inline-block;
  position: relative;
  color: white;
}

.exampleClass::after {
  content: '';
  position: absolute;
  width: 100%;
  transform: scaleX(0);
  height: 2px;
  bottom: 0;
  left: 0;
  background-color: white;
  transform-origin: bottom right;
  transition: transform 0.4s cubic-bezier(0.86, 0, 0.07, 1);
}

.exampleClass:hover::after {
  transform: scaleX(1);
  transform-origin: bottom left;
}
```

The Stitches styles are correct but the CSS and SCSS options get the [underlineLeftRight](https://github.com/emilkowalski/ui-snippets/blob/master/components/Snippets/underlineLeftRight.js)'s style (? . Very glad to help if needed.
